<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mac</string>
	</array>
	<key>name</key>
	<string>RStyle</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.mac</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tab stops like $1, $2...</string>
			<key>match</key>
			<string>\$(\d+)</string>
			<key>name</key>
			<string>keyword.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.mac</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\$)(\{)([0-9]+):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.mac</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.mac</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>variable.complex.mac</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.mac</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\\(\$|\&gt;|\&lt;)</string>
			<key>name</key>
			<string>constant.character.escape.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$)</string>
			<key>name</key>
			<string>invalid.mac</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mac</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.mac</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mac</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.mac</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.mac</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mac</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.mac</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.mac</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.mac</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match regular function like: function myFunc(arg) { … }</string>
			<key>match</key>
			<string>(?i)\b(macro|Macro)\s+([a-zA-Z_$]\w*)?\s*(\()(.*?)(\))</string>
			<key>name</key>
			<string>meta.function.mac</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mac</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mac</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.mac</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.mac</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(bool|Object|class|double|string|cpwin|macro|int|var|(M|m)oney|(F|f)ields|(V|v)alue)\b</string>
			<key>name</key>
			<string>storage.type.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(const|Const|export|private|public|static)\b</string>
			<key>name</key>
			<string>storage.modifier.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(break|continue|else|elif|for|if|import|package|return|(W|w)hile|key|keys|(E(nd|ND)|end))\b</string>
			<key>name</key>
			<string>keyword.control.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\btrue\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bfalse\b</string>
			<key>name</key>
			<string>constant.language.boolean.false.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bnull\b</string>
			<key>name</key>
			<string>constant.language.null.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(super|this)\b</string>
			<key>name</key>
			<string>variable.language.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(debugbreak)\b</string>
			<key>name</key>
			<string>keyword.other.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(CoMainLite|CoMain|Array|TArray|TArrayEx|TCollection|Date|Form|Frame|macro|GenObject|Number|Object|Option|Packages|Password|Plugin|Radio|RegExp|Reset|Select|String|Style|Submit|screen|sun|Text|Caption|window|XMLHttpRequest)\b</string>
			<key>name</key>
			<string>support.class.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b((O|o)nerror|AbortTrn|Abs|GetD(s|S)|MsgBoxErr|GetFullD(s|S)|GetData|DateToString|FirstDayMonth|MarkRow|LastDayMonth|CmdArgs|DtTm|DtTmSplit|GetComputerName|ParseString|IsValueInList|SimpleIf|DateShift|Datesplit|Double|Exec(Macro|Macro2|MacroFile)|GenClassName|GenEnum|GetDouble|GetInt|GetMoney|GetString|GetStringR|GetTrue|Item|Max|MsgBox|DoubleL|Double|Int|Money|Round|Run|SubObjects|RunError|RunMenu|SelectFile|StrBrk|StrFor|StrLen|StrLwr|StrSet|StrSplit|StrSplit2|StrSubst|StrUpr|SubStr|TEnumArray|TestEvent|Time|Date|TimeSplit|ToANSI|ToOEM|TRecHandler|Trim)\b(?=\()</string>
			<key>name</key>
			<string>support.function.mac</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword operators that evaluate to True or False</string>
			<key>match</key>
			<string>(?i)\b(and|in|is|(N|n)ot|NOT|or)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)%|&amp;|\*|\-\-|\-|\+\+|\+|~|==|=|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;|!|\|\||\?\:|\*=|/=|%=|\+=|\-=|&amp;=|\^=|\b(normal|append|blob)\b</string>
			<key>name</key>
			<string>keyword.operator.mac</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=[=(:]|^|return|&amp;&amp;|\|\||!)\s*(/)(?![/*+{}?])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mac</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/)[igm]*</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mac</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.regexp.mac</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.mac</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>punctuation.terminator.statement.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>,[ |\t]*</string>
			<key>name</key>
			<string>meta.delimiter.object.comma.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.delimiter.method.period.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round.mac</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>meta.brace.square.mac</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mac</string>
	<key>uuid</key>
	<string>f24766ec-8d6d-423b-8b09-3f9939e4ff02</string>
</dict>
</plist>
